version: '3'

services:
  data-provider:
    build:
      context: ./data-provider
    container_name: data-provider
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: data_provider_db
      POSTGRES_USER: data_provider_user
      POSTGRES_PASSWORD: data_provider_password
    depends_on:
      - data-provider-db
      - redis
    volumes:
      - ./data-provider:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  data-provider-db:
    image: postgres
    environment:
      POSTGRES_DB: data_provider_db
      POSTGRES_USER: data_provider_user
      POSTGRES_PASSWORD: data_provider_password
    ports:
      - "5432:5432"
    volumes:
      - data_provider_data:/var/lib/postgresql/data

  dashboard-service:
    build:
      context: ./dashboard-service
    container_name: dashboard-service
    ports:
      - "8001:8001"
    depends_on:
      - dashboard-service-db
      - redis
    volumes:
      - ./dashboard-service:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  dashboard-service-db:
    image: postgres
    environment:
      POSTGRES_DB: dashboard_service_db
      POSTGRES_USER: dashboard_service_user
      POSTGRES_PASSWORD: dashboard_service_password
    ports:
      - "5433:5433"
    volumes:
      - dashboard_data:/var/lib/postgresql/data

  celery-worker-dashboard:
    container_name: celery-worker-dashboard
    build: ./dashboard-service
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
      - dashboard-service

  celery-beat-dashboard:
    container_name: celery-beat-dashboard
    build: ./dashboard-service
    command: celery -A app.celery beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  data_provider_data:
  dashboard_data:
